//
//  TestImage.h
//  ProjectName
//
//  Created by Demian Turner on 14/12/2016.
//  Copyright (c) 2016 Seagull Systems. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <Cocoa/Cocoa.h>


@interface TestImage : NSObject

// Generated Images
+ (NSImage *)imageOfMyImage:(int)measurement;

@end
